version: '3.1'
services:
  backendAPI:
    image:
    build:  ./portfolioApi
    restart: always
    ports:
      - 8000:8000

    depends_on:
      - postgres

  frontend:
    image: 
    build:  ./portfolio-front
    restart: always
    ports:
      - 3000:3000

  
  postgres:
    container_name: postgres
    image: postgres
    environment:
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD

    ports:
      - 
    
    command: postgresdb

    volumes:
      - pgdata:/var/postgresql/data

  redis:
        image: redis
        container_name: redis
        ports:
            - '6379:6379'
        environment:
          - REDIS_PASSWORD=

volumes:
  pgdata:

# 