# Generated by Django 4.2.1 on 2023-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_language_link_alter_language_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='preview_img',
        ),
        migrations.AddField(
            model_name='project',
            name='gif',
            field=models.FileField(default=1, upload_to='gifs/'),
            preserve_default=False,
        ),
    ]
