# Generated by Django 4.2.1 on 2023-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
